apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config
  namespace: monitoring
data:
  config.yml: |
    region: us-east-1
    metrics:
      - aws_namespace: AWS/EC2
        aws_metric_name: CPUUtilization
        dimensions: [InstanceId]
        statistics: [Average]
        period_seconds: 300
        range_seconds: 600

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter
  template:
    metadata:
      labels:
        app: cloudwatch-exporter
    spec:
      serviceAccountName: cloudwatch-exporter-sa
      containers:
        - name: cloudwatch-exporter
          image: prom/cloudwatch-exporter
          args:
            - "--config.file=/config/config.yml"
          ports:
            - containerPort: 9106
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: cloudwatch-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
spec:
  selector:
    app: cloudwatch-exporter
  ports:
    - name: http
      port: 9106
      targetPort: 9106
